apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: mlflow
  name: mlflow
  namespace: kubeflow
spec:
  containers:
  - name: mlflow
    image: ghcr.io/mlflow/mlflow:v2.7.1
    command: ["mlflow", "server"]
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: kubeflow
spec:
  selector:
    app.kubernetes.io/name: mlflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000