apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: mlflow-server-service
spec:
  selector:
    app.kubernetes.io/name: mlflow-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
