replicaCount: 1

image:
  repository: ghcr.io/mlops-for-all/mlflow-tracking-server
  tag: 3.8-1.30.1-v1.0.0
  pullPolicy: IfNotPresent

db:
  backendStoreUri: postgresql://mlops:mlops@postgresql-ha-pgpool.postgresql:5432/mlflow

s3:
  endpointUrl: http://minio-1699344888.minio:9000
  accessKeyId: mlops
  secretAccessKey: mlops123
  bucket: mlflow

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
